version: '3.8'
services:
  backend:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    env_file:
      - .env
    restart: always
