version: '3.8'

services:
  backend:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Add PORT=5003 for NestJS app, DOCKER_HOST_PORT=5003 for public port
      - ${PORT}:${DOCKER_HOST_PORT}
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    restart: always
