export const testNames = [
  'case2xLastBeatAttackerWins',
  'case2xLastRoundDrawWins',
  'case2xLastRoundCardsInDeck',
  'case2xNoCardsFromDealtForDefenderWins',
  'case2xLastRound6x6AttackerWins',
  'case3xDefenderWithNoCards',
  'case3xAttackerWithNoCards',
  'case3xAttackerWithNoCardsNoWins',
  'case3xDefenderLoserWith2Cards',
  'case3xLastRoundDrawWins',
  'case3xDefenderTakes4Cards',
  'case3xTwoOutGameContinues',
  'case4xTwoAttackersAndDefenderOut',
];
