export const MAX_NUMBER_OF_PLAYERS = 4;
export const UNIQUE_LOCALSTORAGE_PREFIX = 'shopot-sinastya-gentoosiast';
export const AVATAR_PREFIX = 'avatar';
export const MINIMUM_NICKNAME_LENGTH = 4;
export const MAXIMUM_NICKNAME_LENGTH = 32;
export const MINIMUM_PASSWORD_LENGTH = 8;
export const REDIRECT_TIMEOUT = 3000;
export const MESSAGE_TIMEOUT = 3000;
export const LOCALSTORAGE_AUTH_KEY = 'authenticated';
export const AVATAR_SIZE = 60; // 60x60 pixels
